import { FileBadge, Layers, ListChecks, MessageSquareQuote, ScrollText, ShieldAlert, Waypoints } from "lucide-react";
import type { ProjectWorkspaceStaticTabDefinition } from "../../projects/workspaceDefinition";

export const projectWorkspaceAgentContributorId = "agent-artifacts";

export const projectWorkspaceAgentTabs: readonly ProjectWorkspaceStaticTabDefinition[] = [
  {
    id: "artifact-requirements",
    kind: "artifact-requirements",
    title: "Requirements",
    group: "artifact",
    intents: ["requirements"],
    treeEntry: { label: "Requirements", icon: FileBadge, color: "blue" },
    badgeKey: "requirements",
  },
  {
    id: "artifact-assumptions",
    kind: "artifact-assumptions",
    title: "Assumptions",
    group: "artifact",
    intents: ["assumptions"],
    treeEntry: { label: "Assumptions", icon: ListChecks, color: "blue" },
    badgeKey: "assumptions",
  },
  {
    id: "artifact-questions",
    kind: "artifact-questions",
    title: "Questions",
    group: "artifact",
    intents: ["questions"],
    treeEntry: { label: "Questions", icon: MessageSquareQuote, color: "blue" },
    badgeKey: "questions",
  },
  {
    id: "artifact-adrs",
    kind: "artifact-adrs",
    title: "ADRs",
    group: "artifact",
    intents: ["adrs"],
    treeEntry: { label: "ADRs", icon: ScrollText, color: "blue" },
    badgeKey: "adrs",
  },
  {
    id: "artifact-findings",
    kind: "artifact-findings",
    title: "Findings",
    group: "artifact",
    intents: ["findings"],
    treeEntry: { label: "Findings", icon: ShieldAlert, color: "blue" },
    badgeKey: "findings",
  },
  {
    id: "artifact-iac",
    kind: "artifact-iac",
    title: "Infrastructure as Code",
    group: "artifact",
    intents: ["iac"],
    treeEntry: { label: "IaC", icon: FileBadge, color: "blue" },
    badgeKey: "iac",
  },
  {
    id: "artifact-costs",
    kind: "artifact-costs",
    title: "Cost Estimates",
    group: "artifact",
    intents: ["costs"],
    treeEntry: { label: "Cost Estimates", icon: FileBadge, color: "blue" },
    badgeKey: "costs",
  },
  {
    id: "artifact-traceability",
    kind: "artifact-traceability",
    title: "Traceability",
    group: "artifact",
    intents: ["traceability"],
    treeEntry: { label: "Traceability", icon: Waypoints, color: "blue" },
    badgeKey: "traceability",
  },
  {
    id: "artifact-candidates",
    kind: "artifact-candidates",
    title: "Candidate Architectures",
    group: "artifact",
    intents: ["candidates"],
    treeEntry: { label: "Candidates", icon: Layers, color: "blue" },
    badgeKey: "candidates",
  },
  {
    id: "artifact-iterations",
    kind: "artifact-iterations",
    title: "Iteration Events",
    group: "artifact",
    intents: ["iterations"],
    treeEntry: { label: "Iterations", icon: MessageSquareQuote, color: "blue" },
    badgeKey: "iterations",
  },
  {
    id: "artifact-mcp",
    kind: "artifact-mcp",
    title: "MCP Queries",
    group: "artifact",
    intents: ["mcp"],
    treeEntry: { label: "MCP Queries", icon: FileBadge, color: "blue" },
    badgeKey: "mcpQueries",
  },
];
